[package]
name = "cctp-rs"
version = "0.2.2"
edition = "2021"
authors = ["Joseph Livesey <joseph@semiotic.ai>"]
categories = ["finance", "api-bindings"]
description = "Rust SDK for CCTP"
homepage = "https://crates.io/crates/cctp-rs"
keywords = ["defi", "ethereum", "web3", "blockchain", "sdk"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/semiotic-ai/cctp-rs"

[dependencies]
alloy-chains = "0.2.0"
alloy-contract = { version = "1.0.3", default-features = false }
alloy-dyn-abi = { version = "1.1.0", default-features = false }
alloy-network = { version = "1.0.3", default-features = false }
alloy-primitives = { version = "1.1.0", default-features = false, features = [
    "std",
    "rlp",
] }
alloy-provider = { version = "1.0.3", default-features = false, features = [
    "anvil-node",
    "reqwest",
] }
alloy-rpc-types = "1.0.3"
alloy-sol-types = { version = "1.1.0", features = ["json"] }
anyhow = "1.0.97"
bon = "3.4.0"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tracing = "0.1.41"
